from pymongo import MongoClient, ASCENDING, DESCENDING
from datetime import datetime
import os


# ------------------------------------------------
# MongoDB Configuration
# ------------------------------------------------

MONGO_URI = os.getenv("MONGO_URI", "mongodb://localhost:27017")
DB_NAME = "log_pipeline"


# ------------------------------------------------
# Connection Setup
# ------------------------------------------------

client = MongoClient(MONGO_URI)

db = client[DB_NAME]

logs_collection = db["logs_parsed"]
alerts_collection = db["alerts"]


# ------------------------------------------------
# Index Creation
# ------------------------------------------------

def create_indexes():
    """
    Create indexes to speed up queries and analytics.
    """

    logs_collection.create_index([("timestamp", DESCENDING)])

    logs_collection.create_index([("level", ASCENDING)])

    logs_collection.create_index([("source_type", ASCENDING)])

    logs_collection.create_index([("service", ASCENDING)])

    logs_collection.create_index([("component", ASCENDING)])

    logs_collection.create_index([("severity_score", DESCENDING)])


# ------------------------------------------------
# Insert Operations
# ------------------------------------------------

def insert_log(log: dict):
    """
    Insert a single parsed log document.
    """

    if not log:
        return

    logs_collection.insert_one(log)


def insert_logs_bulk(logs: list):
    """
    Insert multiple logs efficiently.
    """

    if not logs:
        return

    logs_collection.insert_many(logs)


# ------------------------------------------------
# Alert Storage
# ------------------------------------------------

def insert_alert(alert: dict):
    """
    Insert an alert generated by the alert engine.
    """

    alert["triggered_at"] = datetime.utcnow()

    alerts_collection.insert_one(alert)


# ------------------------------------------------
# Query Helpers
# ------------------------------------------------

def get_recent_logs(limit=50):
    """
    Fetch most recent logs.
    """

    return list(
        logs_collection
        .find()
        .sort("timestamp", DESCENDING)
        .limit(limit)
    )


def get_error_logs(limit=100):
    """
    Fetch recent ERROR and CRITICAL logs.
    """

    return list(
        logs_collection
        .find({"level": {"$in": ["ERROR", "CRITICAL"]}})
        .sort("timestamp", DESCENDING)
        .limit(limit)
    )


def get_log_stats():
    """
    Aggregation for dashboard statistics.
    """

    pipeline = [
        {
            "$group": {
                "_id": "$level",
                "count": {"$sum": 1}
            }
        }
    ]

    return list(logs_collection.aggregate(pipeline))


# ------------------------------------------------
# Health Check
# ------------------------------------------------

def check_connection():
    """
    Verify database connection.
    """

    try:
        client.admin.command("ping")
        return True
    except Exception:
        return False


# ------------------------------------------------
# Initialize DB
# ------------------------------------------------

create_indexes()


